# Generated by Django 4.2.14 on 2025-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeManager', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
